version: '3.8'
services:
  db:
    build: ./mysql
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 33070:3306
    env_file:
      - ./mysql/db-variables.env
    volumes:
    - ./mysql/mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./mysql/myadmin.env
    depends_on:
      - db
    ports:
      - 8778:80

  php:
    build: ./php
    depends_on:
    - db
    ports:
    - 8777:8000
    volumes:
    - ./work:/work
